export const ADD_TO_CART = "ADD_TO_CART";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
